version: "3.8"

services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui-worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - "../../docker-volumes/comfy-volume/data/models:/comfyui/models"
      - "../../docker-volumes/comfy-volume/data/output:/comfyui/output"
      - "./src/extra_model_paths.yaml:/comfyui/extra_model_paths.yaml"
